name: Data Preprocessing Workflow
run-name: ${{ github.actor }} workflow with shared Azure login

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  DataPreprocessingJob:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Clone repository code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Prepare Python environment
      - name: Prepare Python environment
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn joblib numpy azure-cli

      # Azure login 
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      # Set up Azure ML CLI extension
      - name: Install Azure ML extension
        run: |
          az extension add -n ml -y
          az extension update -n ml

      # Verify repository structure
      - name: Verify Repository Structure
        run: |
          pwd
          ls -R

      # Stage 1: Validate input data
      - name: Validate Input Data
        run: |
          test -f PRO/mydata.csv || (echo "Input data file missing" && exit 1)

      # Stage 2: Upload Dataset to Azure ML
      - name: Upload dataset to Azure ML
        run: |
          az ml data create \
            --name raw_data \
            --path PRO/mydata.csv \
            --type uri_file \
            --workspace-name myminiproject \
            --resource-group Miniproject \
            --description "Uploading raw dataset for pre-preprocessing"

      # Stage 3: Run Data Cleaning Script
      - name: Run data cleaning script
        run: |
          python Out/data_cleaning.py \
            --trainingdata "PRO/mydata.csv" \
            --outputmodel "Out/cleaned_data.csv"

      # Stage 4: Verify Cleaned Data
      - name: Verify Cleaned Data
        run: |
          test -f Out/cleaned_data.csv || (echo "Data cleaning failed" && exit 1)
          head -n 5 Out/cleaned_data.csv

      # Stage 5: Upload Cleaned Dataset to Azure ML
      - name: Save cleaned dataset
        run: |
          az ml data create \
            --name cleaned_data \
            --path Out/cleaned_data.csv \
            --type uri_file \
            --workspace-name myminiproject \
            --resource-group Miniproject \
            --description "Saving cleaned dataset for further processing"