name: GitHub Actions Workflow
run-name: ${{ github.actor }} workflow with shared Azure login
on: [push]

jobs:
  DatainjectionJob:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Clone repository code
        uses: actions/checkout@v4

      # Azure login (common step)
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

      # Seting up Azure ML CLI extension (common for Azure ML tasks)
      - name: Install Azure ML extension
        run: |
          az extension add -n ml -y
          az extension update -n ml

      # Stage 1: Upload Dataset
      - name: Upload dataset to Azure ML
        run: |
          az ml data create --name mydata2 \
            --path PROmydata.csv \
            --type uri_file \
            --workspace-name myminiproject \
            --resource-group Miniproject \
            --description "Uploading mydataset in AZ"